### ISSUE TITLE
No menu visible on toggle

### ISSUE THREAD

**Issue by kanjigirl** [micjamking/navigataur#2]
I've gone through this problem for a couple of hours now... what you see here shows only navigataur.css styles, I've removed my stylesheets completely. But the toggle is still not doing anything. My div and menu ul are classed differently than yours, but I changed them line by line in navigataur.css to be sure I didn't miss anything. Please, do you have any other troubleshooting suggestions?

http://www.redkitecreative.com/projects/prsresp/

**Comment by micjamking** [comment]
Hey Deb,

The issue you're experiencing is related to inheritance and your selectors: the guilty code is below:

```
#toggle:checked ~ header#top .menu ul.nav { opacity: 1;}
```

This is incorrect. The CSS general sibling selector `~` allows for selection of any element, following the first specified element within a shared parent container. So it works by taking the first element before the `~` and then looking for any elements following it that match what you specified. In your code, you're basically saying "Look for a `#toggle:checked`, find the `header#top` sibling and then find it's children. Here's what you should do:

```
#top .menu #toggle:checked ~ .nav { opacity: 1; }
```

This says "Look for `#top .menu #toggle:checked` and then find it's `.nav` sibling". I've tested this and it works on your site. 

Also, as a general rule, you don't need to specify the tag selector if it has an associated class/ID, e.g. `header#top`; just `#top` will suffice. Adding the tag name to a selector that has a class or ID slows down the matching process of the browser. [Ref: Mozilla - Writing efficient CSS](https://developer.mozilla.org/en-US/docs/CSS/Writing_Efficient_CSS#Guidelines_for_Efficient_CSS)

Hope this helps and let me know if you have any other questions. Thanks!
- Mike

**Comment by kanjigirl** [comment]
Awesome - thank you so much! Working perfectly now. I don't usually get so specific with tag selectors, just troubleshooting in this case. Thanks again.

**Comment by rcdelacruz82** [comment]
Great responsive navigation. I was wondering if you could help me. The menu is displaying underneath the content. Is there a way to add a slide or place the menu on top of the content. Greatly appreciated. 

Ray

**Comment by micjamking** [comment]
Ray,

I'd be happy to help, but I'll need a bit more information about your setup or a link to the site where this issue exists.

If your issue can be solved by following the comments above or is a separate issue, please open up a new bug report.

If it's not a definitive bug in the code and you would just like help, please move the conversation over to my blog page for the plugin:  http://www.uifuel.com/navigataur-a-pure-css-responsive-navigation-menu/

Thanks,
- Mike
