### ISSUE TITLE
License not specified

### ISSUE THREAD

**Issue by vitorgalvao** [micjamking/navigataur#4]
You have a copyright notice, but since it’s public on github, it should have an open-source license. What are you releasing this under?

If you put a copyright to your name, it would mean no one could use it without your prior consent (essentially useless to who’d want to grab it and use it).

It seems to work fine, so I’d like to know if I can use it for my projects and/or alter it.

**Comment by micjamking** [comment]
Hi Vitor,

Thank you for the reminder, I had originally been meaning to find the appropriate license to place it under, but forgot to get to it. This is now being released under the [BSD 2-Clause Open Source license](http://opensource.org/licenses/bsd-license.php), which states as follows:

```
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Basically, you are free to use & manipulate Navigataur as you would like, but if you plan to redistribute the code, the license needs to go with it (& I'm not liable for any damages).

Hopefully this helps! I'm interested to see what projects you decide to use this in.

Thanks,
Mike
